name: ForexFred
favicon: null
layout_spectrum: 0.5412663950119168
typography_spectrum: 0.46717968210577965
title: ForexFred
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#d3d3d3'
    - '#3b3f42'
    - '#72757b'
    - '#58cdfb'
  brandStrength: 0.9008094477467239
  lightness: 0.4963983311317861
  saturation: 0.6699147908948362
  rhythmicContrast: 0.34199782414361835
purpose: []
